version: "3.7"

services:
  selenium:
    container_name: selenium
    hostname: chrome
    image: selenium/standalone-chrome:latest
    shm_size: 1g
    ports:
      - 4444:4444

  bot:
    container_name: bot
    build: .
    volumes:
      - ./bot:/bot
    depends_on:
      - selenium
    command: tail -F anything